-- This script runs automatically when the database initializes.
-- NOTE: the gvenzl/oracle-free entrypoint runs these scripts as SYS against
-- the root container, so we explicitly connect as the app user to FREEPDB1 —
-- otherwise every object lands in the SYS schema and the Go service
-- (hospital_user@FREEPDB1) cannot see any of it.
CONNECT hospital_user/hospital_password@localhost:1521/FREEPDB1

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE patients (
    patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20) NOT NULL UNIQUE,
    national_id VARCHAR2(20),
    mrn VARCHAR2(20),
    gender VARCHAR2(10),
    dob DATE,
    last_visit DATE,
    medical_history VARCHAR2(500)
);

CREATE TABLE departments (
    department_id NUMBER PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    branch VARCHAR2(50) NOT NULL,
    CONSTRAINT uq_department UNIQUE (name, branch)
);

CREATE TABLE doctors (
    doctor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    specialty VARCHAR2(150),
    department_id NUMBER NOT NULL REFERENCES departments(department_id)
);

CREATE TABLE doctor_availability (
    availability_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id NUMBER NOT NULL REFERENCES doctors(doctor_id),
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    is_booked NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE appointments (
    appointment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id NUMBER REFERENCES patients(patient_id),
    doctor_id NUMBER REFERENCES doctors(doctor_id),
    availability_id NUMBER REFERENCES doctor_availability(availability_id),
    appointment_date TIMESTAMP NOT NULL,
    reason VARCHAR2(200),
    status VARCHAR2(20) DEFAULT 'SCHEDULED'
);

CREATE INDEX idx_avail_doctor_time ON doctor_availability (doctor_id, start_time);
CREATE INDEX idx_appt_patient ON appointments (patient_id);

-- ============================================================
-- DEPARTMENTS (Magrabi Health UAE: Eye Care at all 4 branches,
-- ENT Care at Abu Dhabi ONLY)
-- ============================================================

INSERT INTO departments (department_id, name, branch) VALUES (1, 'Eye Care', 'Dubai DHCC');
INSERT INTO departments (department_id, name, branch) VALUES (2, 'Eye Care', 'Abu Dhabi');
INSERT INTO departments (department_id, name, branch) VALUES (3, 'Eye Care', 'Al Ain');
INSERT INTO departments (department_id, name, branch) VALUES (4, 'Eye Care', 'Mirdif');
INSERT INTO departments (department_id, name, branch) VALUES (5, 'ENT Care', 'Abu Dhabi');

-- ============================================================
-- DOCTORS (real Magrabi Health UAE roster from magrabihealth.ae;
-- branch assignment is demo mock data)
-- ============================================================

-- Dubai DHCC — Eye Care
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Mohammad Hesham Aly', 'Medical Director; Cataract and Glaucoma Consultant', 1);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Moataz Sallam', 'Consultant, Cataract, Refractive and Anterior Segment Surgery (LASIK)', 1);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Lama ElJurdi', 'Oculoplastic Surgeon (Oculoplasty unit)', 1);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Amr Faried', 'Vitreo-Retina Specialist', 1);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Hala Lotfi', 'Specialist Ophthalmology', 1);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Mohamed Mounir', 'Ophthalmology Specialist', 1);

-- Abu Dhabi — Eye Care
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Tamer Gamaly', 'Consultant Ophthalmology', 2);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Hassan Sabri', 'Consultant Ophthalmology', 2);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Kamal Mehrez', 'Consultant Ophthalmology', 2);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Ahmed Naeim', 'Specialist Ophthalmology', 2);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Riham Afifi', 'Specialist Ophthalmology', 2);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Omar Abu Suud', 'Specialist Ophthalmologist', 2);

-- Al Ain — Eye Care
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Hisham Hamdy', 'Consultant Ophthalmology', 3);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Wael El Manawy', 'Consultant Ophthalmology', 3);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Khaled Abdeen', 'Specialist Ophthalmology', 3);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Mohamed Ahmed Abdelhafez', 'Ophthalmology Specialist', 3);

-- Mirdif — Eye Care
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Hisham Hasby', 'Consultant Ophthalmologist', 4);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Ossama Abd ElHakim', 'Ophthalmology Consultant', 4);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Mohammed Kaoud', 'Specialist Ophthalmology', 4);
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Randa Kashif', 'Ophthalmology Specialist', 4);

-- Abu Dhabi — ENT Care (the only ENT branch)
INSERT INTO doctors (name, specialty, department_id) VALUES ('Dr. Ahmed Morsi', 'Consultant Otolaryngology (ENT)', 5);

-- ============================================================
-- MOCK AVAILABILITY
-- 30-minute slots, 9:00 AM to 5:00 PM, for the next 14 days,
-- for every doctor. Roughly 30% of slots are randomly pre-booked
-- so availability looks realistic in the demo.
-- ============================================================

BEGIN
    FOR doc IN (SELECT doctor_id FROM doctors) LOOP
        FOR day_offset IN 0..13 LOOP
            FOR slot_num IN 0..15 LOOP
                INSERT INTO doctor_availability (doctor_id, start_time, end_time, is_booked)
                VALUES (
                    doc.doctor_id,
                    CAST(TRUNC(SYSDATE) + day_offset AS TIMESTAMP) + NUMTODSINTERVAL(9 * 60 + slot_num * 30, 'MINUTE'),
                    CAST(TRUNC(SYSDATE) + day_offset AS TIMESTAMP) + NUMTODSINTERVAL(9 * 60 + slot_num * 30 + 30, 'MINUTE'),
                    CASE WHEN DBMS_RANDOM.VALUE(0, 1) < 0.3 THEN 1 ELSE 0 END
                );
            END LOOP;
        END LOOP;
    END LOOP;
    COMMIT;
END;
/

-- ============================================================
-- MOCK PATIENTS (UAE-style demo data)
-- ============================================================

INSERT INTO patients (name, phone, national_id, mrn, gender, dob, last_visit, medical_history)
VALUES ('Ahmed Al Mansouri', '+971501234567', '1012345678', 'MRN-000001', 'Male', TO_DATE('1985-05-15', 'YYYY-MM-DD'), TO_DATE('2026-03-10', 'YYYY-MM-DD'), 'Type 2 diabetes. Annual diabetic retina screening at Dubai DHCC. No known allergies.');

INSERT INTO patients (name, phone, national_id, mrn, gender, dob, last_visit, medical_history)
VALUES ('Fatima Hassan', '+971529876543', '2098765432', 'MRN-000002', 'Female', TO_DATE('1990-12-10', 'YYYY-MM-DD'), TO_DATE('2026-05-22', 'YYYY-MM-DD'), 'Myopia, wears contact lenses. Interested in LASIK assessment. Allergic to penicillin.');

INSERT INTO patients (name, phone, national_id, mrn, gender, dob, last_visit, medical_history)
VALUES ('Sarah Thompson', '+971567654321', '2076543210', 'MRN-000003', 'Female', TO_DATE('1978-08-02', 'YYYY-MM-DD'), TO_DATE('2026-01-18', 'YYYY-MM-DD'), 'Chronic sinusitis, follow-up with ENT at Abu Dhabi branch. No known drug allergies.');

COMMIT;
