name: Deploy Invygo Service

on:
  push:
    branches:
      - feature/invygo-trial

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER_STAGING }}
          key: ${{ secrets.EC2_SSH_KEY_STAGING }}
          script: |
            cd ~/convoi_ai/invygo-go-service
            
            # Running your manual commands
            git pull origin feature/invygo-trial
            go build -o invygo-service
            sudo systemctl daemon-reload
            sudo systemctl restart invygo.service
